export enum ActionType {
    ADD_SONG_FILE = "ADD_SONG_FILE",
    REMOVE_SONG_FILE = "REMOVE_SONG_FILE",
    ADD_ARTWORK_FILE = "ADD_ARTWORK_FILE",
    REMOVE_ARTWORK_FILE = "REMOVE_ARTWORK_FILE",
    SET_IS_UPLOADING = "SET_IS_UPLOADING",
    CHANGE_SONGS_PAGE = "CHANGE_SONGS_PAGE"
}